<a href="https://colab.research.google.com/github/amosagekouassi-source/DI-Bootcamp/blob/master/Exercice_XP_J1_W3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Exercie 1:Array Creation and Manipulation

#Create a 1D NumPy array containing numbers from 0 to 9.
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#Exercice 2:Type Conversion and Array Operations

#Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
array_1 = np.array([3.14, 2.17, 0, 1, 2])
print(array_1.dtype)
array_1 = array_1.astype(int)
print(array_1.dtype)
print(array_1)

float64
int64
[3 2 0 1 2]


In [14]:
#Exercice 3:  Working with Multi-Dimensional Arrays

#Create a 3x3 NumPy array with values ranging from 1 to 9.
array_2 = np.arange(1, 10)
array_3 = array_2.reshape(3, 3)
print(array_2)
print(array_3)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#Exercice 4: Creating Multi-Dimensional Array with Random Numbers

#Create a 2D NumPy array of shape (4, 5) filled with random numbers.
random_array = np.random.rand(4, 5)
print(random_array)

[[2.07071091e-01 9.63378856e-01 5.67572057e-01 8.18200624e-01
  5.47465963e-01]
 [1.52317315e-01 7.99519591e-01 8.01830620e-01 1.48702374e-01
  9.58279126e-04]
 [1.69625419e-01 9.15321733e-01 1.96524071e-01 9.41389082e-01
  9.44425498e-01]
 [3.74743015e-01 1.11184636e-01 4.15330277e-01 8.74863478e-01
  5.51809460e-01]]


In [19]:
#Exrecice 5: Indexing Arrays

#Select the second row from a given 2D NumPy array.
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1, :])

[20 21 22 23 24]


In [28]:
#Exercice 6: Reversing elements

#Reverse the order of elements in a given 1D NumPy array (first element becomes last).
array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
new = np.flip(array)
print(new)

[0 1 2 3 4 5 6 7 8 9]


In [1]:
#Exercice 7: Identity Matrix

#Create a 4x4 identity matrix using NumPy
import numpy as np

A = np.arange(16).reshape(4,4)

I = (A % 5 == 0).astype(int)

print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
#Exercice 8: Simple Aggregate Funcs

#Find the sum and average of a given 1D array
new = np.arange(10)
print("array:", new)
print("sum:", np.sum(new))
print("average:", np.mean(new))

array: [0 1 2 3 4 5 6 7 8 9]
sum: 45
average: 4.5


In [6]:
# Exercise 9 : Create Array and Change its Structure

#Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.
new = np.arange(1, 21)
new = new.reshape(4, 5)
print(new)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
#Exercise 10 : Conditional Selection of Values

#Extract all odd numbers from a given NumPy array.
arr = np.arange(10)
print("Odd numbers:", arr[arr % 2 == 1])

Odd numbers: [1 3 5 7 9]
